// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShenzhenLhgs.Database;

#nullable disable

namespace ShenzhenLhgs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ShenzhenLhgs.Models.AjfRanking", b =>
                {
                    b.Property<string>("Shoulhzh")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "shoulhzh");

                    b.Property<string>("Area")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "area");

                    b.Property<int>("AreaPaix")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "areaPaix");

                    b.Property<string>("Batch")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "batch");

                    b.Property<string>("Chengylx")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "chengylx");

                    b.Property<string>("CreateId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "createId");

                    b.Property<string>("CreateTime")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "createTime");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "createUser");

                    b.Property<string>("DgsBatchId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "dgsBatchId");

                    b.Property<string>("Gongszt")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "gongszt");

                    b.Property<string>("Hujszq")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "hujszq");

                    b.Property<string>("Hunyzk")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "hunyzk");

                    b.Property<string>("Juzdszjd")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "juzdszjd");

                    b.Property<string>("Juzdszq")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "juzdszq");

                    b.Property<string>("LhmcId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lhmcId");

                    b.Property<string>("Lianxdh")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lianxdh");

                    b.Property<string>("Lunhlb")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lunhlb");

                    b.Property<string>("Num")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "num");

                    b.Property<int>("Numpaix")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "numpaix");

                    b.Property<string>("OutTime")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "outTime");

                    b.Property<string>("OutlhFlag")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "outlhFlag");

                    b.Property<int>("Paix")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "paix");

                    b.Property<string>("PersonType")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "personType");

                    b.Property<string>("QuaDate")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "quaDate");

                    b.Property<string>("QuaExplain")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "quaExplain");

                    b.Property<string>("Qyybzj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "qyybzj");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "remark");

                    b.Property<string>("Rgqk")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rgqk");

                    b.Property<string>("Rucsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rucsj");

                    b.Property<string>("Ruhsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "ruhsj");

                    b.Property<string>("Rzqk")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rzqk");

                    b.Property<string>("SeqNo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "seqNo");

                    b.Property<string>("Sfzh")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "sfzh");

                    b.Property<string>("Shenfzh")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shenfzh");

                    b.Property<string>("Shenqlb")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shenqlb");

                    b.Property<string>("Shifcj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shifcj");

                    b.Property<string>("Shifrc")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shifrc");

                    b.Property<string>("Shifzsqr")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shifzsqr");

                    b.Property<string>("Shouccbsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shouccbsj");

                    b.Property<string>("ShouccbsjAj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shouccbsjAj");

                    b.Property<string>("ShouccbsjGz")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shouccbsjGz");

                    b.Property<string>("Sjqrly")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sjqrly");

                    b.Property<string>("Sjqrsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sjqrsj");

                    b.Property<string>("SlbahzId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "slbahzId");

                    b.Property<string>("SqbId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sqbId");

                    b.Property<string>("SqcyxxbId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sqcyxxbId");

                    b.Property<string>("UpdateId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "updateId");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "updateTime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "updateUser");

                    b.Property<string>("WaitFlag")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "waitFlag");

                    b.Property<string>("WaitTpye")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "waitTpye");

                    b.Property<string>("WaitTpyeCode")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "waitTpyeCode");

                    b.Property<string>("Xingm")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "xingm");

                    b.HasKey("Shoulhzh");

                    b.HasIndex("Sfzh");

                    b.HasIndex("Xingm");

                    b.ToTable("AjfRankings");
                });

            modelBuilder.Entity("ShenzhenLhgs.Models.GzfRanking", b =>
                {
                    b.Property<string>("Shoulhzh")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "shoulhzh");

                    b.Property<string>("Area")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "area");

                    b.Property<int>("AreaPaix")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "areaPaix");

                    b.Property<string>("Batch")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "batch");

                    b.Property<string>("Chengylx")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "chengylx");

                    b.Property<string>("CreateId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "createId");

                    b.Property<string>("CreateTime")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "createTime");

                    b.Property<string>("CreateUser")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "createUser");

                    b.Property<string>("DgsBatchId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "dgsBatchId");

                    b.Property<string>("Gongszt")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "gongszt");

                    b.Property<string>("Hujszq")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "hujszq");

                    b.Property<string>("Hunyzk")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "hunyzk");

                    b.Property<string>("Juzdszjd")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "juzdszjd");

                    b.Property<string>("Juzdszq")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "juzdszq");

                    b.Property<string>("LhmcId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lhmcId");

                    b.Property<string>("Lianxdh")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lianxdh");

                    b.Property<string>("Lunhlb")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lunhlb");

                    b.Property<string>("Num")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "num");

                    b.Property<int?>("Numpaix")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "numpaix");

                    b.Property<string>("OutTime")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "outTime");

                    b.Property<string>("OutlhFlag")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "outlhFlag");

                    b.Property<int>("Paix")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "paix");

                    b.Property<string>("PersonType")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "personType");

                    b.Property<string>("QuaDate")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "quaDate");

                    b.Property<string>("QuaExplain")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "quaExplain");

                    b.Property<string>("Qyybzj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "qyybzj");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "remark");

                    b.Property<string>("Rgqk")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rgqk");

                    b.Property<string>("Rucsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rucsj");

                    b.Property<string>("Ruhsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "ruhsj");

                    b.Property<string>("Rzqk")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rzqk");

                    b.Property<string>("SeqNo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "seqNo");

                    b.Property<string>("Sfzh")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "sfzh");

                    b.Property<string>("Shenfzh")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shenfzh");

                    b.Property<string>("Shenqlb")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shenqlb");

                    b.Property<string>("Shifcj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shifcj");

                    b.Property<string>("Shifrc")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shifrc");

                    b.Property<string>("Shifzsqr")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shifzsqr");

                    b.Property<string>("Shouccbsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shouccbsj");

                    b.Property<string>("ShouccbsjAj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shouccbsjAj");

                    b.Property<string>("ShouccbsjGz")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "shouccbsjGz");

                    b.Property<string>("Sjqrly")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sjqrly");

                    b.Property<string>("Sjqrsj")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sjqrsj");

                    b.Property<string>("SlbahzId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "slbahzId");

                    b.Property<string>("SqbId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sqbId");

                    b.Property<string>("SqcyxxbId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sqcyxxbId");

                    b.Property<string>("UpdateId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "updateId");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "updateTime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "updateUser");

                    b.Property<string>("WaitFlag")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "waitFlag");

                    b.Property<string>("WaitTpye")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "waitTpye");

                    b.Property<string>("WaitTpyeCode")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "waitTpyeCode");

                    b.Property<string>("Xingm")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "xingm");

                    b.HasKey("Shoulhzh");

                    b.HasIndex("Sfzh");

                    b.HasIndex("Xingm");

                    b.ToTable("GzfRankings");
                });
#pragma warning restore 612, 618
        }
    }
}
